[package]
name = "zingo-memo"
version = "0.1.0"
edition = "2021"

[dependencies]
zcash_address.workspace = true
zcash_client_backend.workspace = true
zcash_encoding.workspace = true
zcash_keys.workspace = true
zcash_primitives.workspace = true
