[package]
name = "zingo-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
zingolib = { path = "../zingolib/", features = ["deprecations"] }
zingoconfig = { path = "../zingoconfig/" }
zingo-testutils = { path = "../zingo-testutils" }

clap = { workspace = true }
http = { workspace = true }

rustyline = "11.0.0"
log = "0.4.17"
shellwords = "1.1.0"
json = "0.12.4"
